// Generated by gencpp from file action_primitive_variation/MoveArm.msg
// DO NOT EDIT!


#ifndef ACTION_PRIMITIVE_VARIATION_MESSAGE_MOVEARM_H
#define ACTION_PRIMITIVE_VARIATION_MESSAGE_MOVEARM_H

#include <ros/service_traits.h>


#include <action_primitive_variation/MoveArmRequest.h>
#include <action_primitive_variation/MoveArmResponse.h>


namespace action_primitive_variation
{

struct MoveArm
{

typedef MoveArmRequest Request;
typedef MoveArmResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct MoveArm
} // namespace action_primitive_variation


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::action_primitive_variation::MoveArm > {
  static const char* value()
  {
    return "dabfe91d481ed6e7759f42648158bcae";
  }

  static const char* value(const ::action_primitive_variation::MoveArm&) { return value(); }
};

template<>
struct DataType< ::action_primitive_variation::MoveArm > {
  static const char* value()
  {
    return "action_primitive_variation/MoveArm";
  }

  static const char* value(const ::action_primitive_variation::MoveArm&) { return value(); }
};


// service_traits::MD5Sum< ::action_primitive_variation::MoveArmRequest> should match 
// service_traits::MD5Sum< ::action_primitive_variation::MoveArm > 
template<>
struct MD5Sum< ::action_primitive_variation::MoveArmRequest>
{
  static const char* value()
  {
    return MD5Sum< ::action_primitive_variation::MoveArm >::value();
  }
  static const char* value(const ::action_primitive_variation::MoveArmRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::action_primitive_variation::MoveArmRequest> should match 
// service_traits::DataType< ::action_primitive_variation::MoveArm > 
template<>
struct DataType< ::action_primitive_variation::MoveArmRequest>
{
  static const char* value()
  {
    return DataType< ::action_primitive_variation::MoveArm >::value();
  }
  static const char* value(const ::action_primitive_variation::MoveArmRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::action_primitive_variation::MoveArmResponse> should match 
// service_traits::MD5Sum< ::action_primitive_variation::MoveArm > 
template<>
struct MD5Sum< ::action_primitive_variation::MoveArmResponse>
{
  static const char* value()
  {
    return MD5Sum< ::action_primitive_variation::MoveArm >::value();
  }
  static const char* value(const ::action_primitive_variation::MoveArmResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::action_primitive_variation::MoveArmResponse> should match 
// service_traits::DataType< ::action_primitive_variation::MoveArm > 
template<>
struct DataType< ::action_primitive_variation::MoveArmResponse>
{
  static const char* value()
  {
    return DataType< ::action_primitive_variation::MoveArm >::value();
  }
  static const char* value(const ::action_primitive_variation::MoveArmResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ACTION_PRIMITIVE_VARIATION_MESSAGE_MOVEARM_H
