// Generated by gencpp from file action_primitive_variation/PushButtonRequest.msg
// DO NOT EDIT!


#ifndef ACTION_PRIMITIVE_VARIATION_MESSAGE_PUSHBUTTONREQUEST_H
#define ACTION_PRIMITIVE_VARIATION_MESSAGE_PUSHBUTTONREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace action_primitive_variation
{
template <class ContainerAllocator>
struct PushButtonRequest_
{
  typedef PushButtonRequest_<ContainerAllocator> Type;

  PushButtonRequest_()
    : button_name()  {
    }
  PushButtonRequest_(const ContainerAllocator& _alloc)
    : button_name(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _button_name_type;
  _button_name_type button_name;





  typedef boost::shared_ptr< ::action_primitive_variation::PushButtonRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::action_primitive_variation::PushButtonRequest_<ContainerAllocator> const> ConstPtr;

}; // struct PushButtonRequest_

typedef ::action_primitive_variation::PushButtonRequest_<std::allocator<void> > PushButtonRequest;

typedef boost::shared_ptr< ::action_primitive_variation::PushButtonRequest > PushButtonRequestPtr;
typedef boost::shared_ptr< ::action_primitive_variation::PushButtonRequest const> PushButtonRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::action_primitive_variation::PushButtonRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::action_primitive_variation::PushButtonRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace action_primitive_variation

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'action_primitive_variation': ['/home/Mateo/ros_ws/src/action_primitive_variation/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::action_primitive_variation::PushButtonRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::action_primitive_variation::PushButtonRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::action_primitive_variation::PushButtonRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::action_primitive_variation::PushButtonRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::action_primitive_variation::PushButtonRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::action_primitive_variation::PushButtonRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::action_primitive_variation::PushButtonRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "c456d5069b47e76bc7a03939bbb2aaf4";
  }

  static const char* value(const ::action_primitive_variation::PushButtonRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xc456d5069b47e76bULL;
  static const uint64_t static_value2 = 0xc7a03939bbb2aaf4ULL;
};

template<class ContainerAllocator>
struct DataType< ::action_primitive_variation::PushButtonRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "action_primitive_variation/PushButtonRequest";
  }

  static const char* value(const ::action_primitive_variation::PushButtonRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::action_primitive_variation::PushButtonRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string button_name\n\
";
  }

  static const char* value(const ::action_primitive_variation::PushButtonRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::action_primitive_variation::PushButtonRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.button_name);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct PushButtonRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::action_primitive_variation::PushButtonRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::action_primitive_variation::PushButtonRequest_<ContainerAllocator>& v)
  {
    s << indent << "button_name: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.button_name);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ACTION_PRIMITIVE_VARIATION_MESSAGE_PUSHBUTTONREQUEST_H
