// Generated by gencpp from file action_primitive_variation/PushButton.msg
// DO NOT EDIT!


#ifndef ACTION_PRIMITIVE_VARIATION_MESSAGE_PUSHBUTTON_H
#define ACTION_PRIMITIVE_VARIATION_MESSAGE_PUSHBUTTON_H

#include <ros/service_traits.h>


#include <action_primitive_variation/PushButtonRequest.h>
#include <action_primitive_variation/PushButtonResponse.h>


namespace action_primitive_variation
{

struct PushButton
{

typedef PushButtonRequest Request;
typedef PushButtonResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct PushButton
} // namespace action_primitive_variation


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::action_primitive_variation::PushButton > {
  static const char* value()
  {
    return "06b0fa47749790f71d50d61e72fea1cc";
  }

  static const char* value(const ::action_primitive_variation::PushButton&) { return value(); }
};

template<>
struct DataType< ::action_primitive_variation::PushButton > {
  static const char* value()
  {
    return "action_primitive_variation/PushButton";
  }

  static const char* value(const ::action_primitive_variation::PushButton&) { return value(); }
};


// service_traits::MD5Sum< ::action_primitive_variation::PushButtonRequest> should match 
// service_traits::MD5Sum< ::action_primitive_variation::PushButton > 
template<>
struct MD5Sum< ::action_primitive_variation::PushButtonRequest>
{
  static const char* value()
  {
    return MD5Sum< ::action_primitive_variation::PushButton >::value();
  }
  static const char* value(const ::action_primitive_variation::PushButtonRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::action_primitive_variation::PushButtonRequest> should match 
// service_traits::DataType< ::action_primitive_variation::PushButton > 
template<>
struct DataType< ::action_primitive_variation::PushButtonRequest>
{
  static const char* value()
  {
    return DataType< ::action_primitive_variation::PushButton >::value();
  }
  static const char* value(const ::action_primitive_variation::PushButtonRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::action_primitive_variation::PushButtonResponse> should match 
// service_traits::MD5Sum< ::action_primitive_variation::PushButton > 
template<>
struct MD5Sum< ::action_primitive_variation::PushButtonResponse>
{
  static const char* value()
  {
    return MD5Sum< ::action_primitive_variation::PushButton >::value();
  }
  static const char* value(const ::action_primitive_variation::PushButtonResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::action_primitive_variation::PushButtonResponse> should match 
// service_traits::DataType< ::action_primitive_variation::PushButton > 
template<>
struct DataType< ::action_primitive_variation::PushButtonResponse>
{
  static const char* value()
  {
    return DataType< ::action_primitive_variation::PushButton >::value();
  }
  static const char* value(const ::action_primitive_variation::PushButtonResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ACTION_PRIMITIVE_VARIATION_MESSAGE_PUSHBUTTON_H
