cafe_table:
  # Publish all joint states -----------------------------------
  joint_wall_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50  

  # Position Controllers ---------------------------------------
  joint_wall_position_controller:
    type: effort_controllers/JointPositionController
    joint: joint_wall
    pid: {p: 100.0, i: 0.01, d: 10.0}

